const meta = {
  "intro-to-javascript": "Introduction to JavaScript",
  "javascript-interpreter": "How JavaScript is Interpreted",
  comments: "Comments in JavaScript",
  variables: "Variables",
  "arithmetic-operators": "Arithmetic Operators",
  "logical-operators": "Logical Operators",
  "comparison-operators": "Comparison Operators",
  "control-flow": "Control Flow and Conditional Statements",
  loops: "Loops",
  "data-types": "Data Types",
  "the-typeof-operator": "The typeof Operator",
  functions: "Functions",
  "arrow-functions": "Arrow Functions",
  "async-await": "Async / Await",
  promises: "Promises",
  callbacks: "Callbacks",
  closures: "Closures",
  arrays: "Arrays",
  "sorting-arrays": "JS Sorting Arrays",
  objects: "Objects",
  destructuring: "Array and Object Destructuring",
  strings: "Strings",
  "data-structures": "Data Structures",
  classes: "Classes",
  dates: "Dates",
  bigint: "BigInt",
  "error-handling-and-debugging": "Error Handling and Debugging",
  hoisting: "Hoisting",
  debouncing: "Debouncing",
  throttling: "Throttling",
  "javascript-errors": "JavaScript Errors",
  "reserved-words": "JavaScript Reserved Words",
  "manipulating-the-dom": "Manipulating the DOM",
  "javascript-apis": "JavaScript Built-in APIs",
};

export default meta;
