const meta = {
  css: "What Is CSS?",
  "why-css": "Why Use CSS?",
  "css-syntax": "CSS Syntax",
  "css-comments": "Comments In CSS",
  "css-selectors": "CSS Selectors",
  cascading: "The Cascading Nature Of CSS",
  "css-box-model": "The CSS Box Model",
  "css-properties": "CSS Properties",
  "css-vendor-prefixes": "CSS Vendor Prefixes",
  "css-rules": "CSS At Rules",
  "media-queries": "CSS Media Queries And Responsiveness",
  "deeply-nested-elements": "How to Style Deeply Nested Elements",
  "css-functions": "CSS Functions",
  "css-variables": "CSS Variables",
  "css-units": "CSS Units",
  "css-pseudo-classes": "CSS Pseudo Classes",
  "css-pseudo-elements": "CSS Pseudo Elements",
  "css-colors": "Colors",
  "css-color-gradients": "Color Gradients",
  "css-flexbox": "CSS Flexbox Deep Dive",
  "css-grid": "CSS Grid Deep Dive",
  "css-positioning": "CSS Positioning",
  "working-with-fonts": "Working With Fonts",
  "css-global-styles": "CSS Global Styles",
  "css-animations": "Adding Animations To Webpages",
  "css-entities": "CSS Entities",
  "css-preprocessors": "CSS Preprocessors",
  "css-cross-browser-compatibility": "Cross Browser Compatibility",
};

export default meta;
